### ISSUE TITLE
자바스크립트란?

### ISSUE THREAD

**Issue by GodChiken** [GodChiken/StudyES5#1]
자바스크립트란 무엇인가 한번 짚고 넘어간다.

**Comment by GodChiken** [comment]
### 버전별 특징


버전 | 출시년도 | 특징
-- | -- | --
ES1 | 1997 | 초판
ES2 | 1998 | ISO/IEC   16262 국제 표준과 동일한 규격을 적용
ES3 | 1999 | 정규 표현식,   try…catch 예외 처리
ES5 | 2009 | HTML5와   함께 출현한 표준안. JSON, strict mode, 접근자 프로퍼티(getter, setter), 향상된 배열 조작   기능(forEach, map, filter, reduce, some, every)
ES6   (ECMAScript 2015) | 2015 | let,   const, class, 화살표 함수, 템플릿 리터럴, 디스트럭처링 할당, spread 문법, rest 파라미터, Symbol,   Promise, Map/Set, iterator/generator, module import/export
ES7   (ECMAScript 2016) | 2016 | 지수(**)   연산자, Array.prototype.includes, String.prototype.includes
ES8   (ECMAScript 2017) | 2017 | async/await,   Object 정적 메소드(Object.values, Object.entries,   Object.getOwnPropertyDescriptors)
ES9   (ECMAScript 2018) | 2018 | Object Rest/Spread 프로퍼티

### 브라우저 지원현황

![image](https://user-images.githubusercontent.com/16012504/64072064-77ac9980-ccc3-11e9-9d25-b470a033a688.png)

### Javascript? ECMAScript

* ECMAScript는 자바스크립트의 표준 명세인 ECMA-262를 말하며 프로그래밍 언어의 타입, 값, 객체와 프로퍼티, 함수, 빌트인 객체 등 핵심 문법(core syntax)을 규정한다. 각 브라우저 제조사는 ECMAScript를 준수하여 브라우저에 내장되는 자바스크립트 엔진을 구현한다. 자바스크립트는 일반적으로 프로그래밍 언어로서 기본 뼈대를 이루는 ECMAScript와 브라우저가 별도 지원하는 클라이언트 사이드 Web API, 즉 DOM, BOM, Canvas, XMLHttpRequest, Fetch, requestAnimationFrame, SVG, Web Storage, Web Component, Web worker 등을 아우르는 개념이다. 클라이언트 사이드 Web API는 ECMAScript와는 별도로 World Wide Web Consortium (W3C)에서 별도의 명세로 관리하고 있다. 클라이언트 사이드 Web API의 자세한 내용은 MDN web docs: Web API를 참고하기 바란다.

**Comment by chbaefront** [comment]
오우 야스
