### ISSUE TITLE
문법

### ISSUE THREAD

**Issue by GodChiken** [GodChiken/StudyES5#2]
자바스크립트 문법을 정리한다.

**Comment by GodChiken** [comment]
# 어휘구조
### 유니코드
* 자바스크립트는 유니코드 문자 집합을 사용해서 작성이 된다.
* 유니코드에 관한 특징은 다음과 같다.
    * 대소문자를 구분하여 사용한다.
    * 키워드,변수,이름,숫자 등 토큰들 사이에 공백을 무시한다.       
        > 토큰은 프로그래밍 언어에서 나눌 수 없는 최소 단위        
    * 유니코드 문자를 사용할 수 없는 환경에서 사용할 수 있는 일련의 6자리의 아스키 문자열 시퀀스를 정의가 되있고 대채를 하는 편이다.
### 주석
* 특별히 정리를 할 이유가 없기에 넘어간다.
### 리터럴
* 리터럴이란 프로그램에 직접 나타나는 데이터의 값을 의마하는 단어로 이해하고 넘어간다.
### 식별자와 예약어 
* camel case 방식으로 식별자(변수명)을 선언하며 사용하고 있다. 넘어간다.
* 당연한 이야기이겠지만, 몰랐을때 예약어를 입력하는 경우는 있어도 한번 알고나서 입력하는 바보는 없다.
* 나머자는 거의 다른 언어에서도 쓰임직한 예약어들이 많았으나, *debugger* 는 console.log() 혹은 console.table() 를 대처해서 사용하고 있다.
* 이 외에도 ECMAScript5 에서 사용은 하지 않지만 키워드로 지정되는 것도 존재한다. 다음버전을 위해 미리 기입해논 느낌이다.
* 어짜피 세상이 좋아져서 쓰면 안되는 예약어는 이미 에디터 상에서 걸러진다.
### 선택자와 세미콜론
* 세상 멍청한 자가 아니라면 이런 식으로 입력하지 않겠지만, 한번 짚고 넘어가본다.   
   ```
   var x = 1;
   var y = 1;
   
   
   // 이외같이 겹쳐있는 경우 줄 바꿈을 세미콜론으로 인식하기 때문에 주의한다.
   x
   ++
   y
   
   console.log(x);              // 1 
   console.log(y);              // 2
   ```

**Comment by chbaefront** [comment]
오우 문법 이예
